name: Build and Test

on:
  pull_request:
    branches: [ "main", "develop"]
  push:
    tags: 
      - 'release-v*'
    
jobs:
    setup:
      name: Setup
      runs-on: windows-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
          
      - name: 'Install Latest .NET MAUI Workload'
        run: dotnet workload install maui

      - name: Install dependencies
        run: dotnet restore
        
    build:
      name: Build
      runs-on: windows-latest
      needs: setup
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Build
          run: dotnet build -c Release
          
        - name: Upload build artifacts
          uses: actions/upload-artifact@v3
          with:
            name: build-artifacts
            path: |
              **/bin/Release/
              **/obj/Release/
      
    test:
      name: Test
      runs-on: windows-latest
      needs: [setup, build]
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Download build artifacts
          uses: actions/download-artifact@v3
          with:
            name: build-artifacts

        - name: Test
          run: dotnet test -c Release --no-build --verbosity normal --logger "trx;LogFileName=..\..\..\TestResults.trx"

        - name: Upload test results
          uses: actions/upload-artifact@v3
          with:
            name: tests-result-artifacts
            path: TestResults.trx
            
    report:
      name: Report test results
      runs-on: ubuntu-latest
      needs: [setup, build, test]
      steps:
        - name: Download test results
          uses: actions/download-artifact@v3
          with:
            name: tests-result-artifacts

        - name: Publish Test Results
          uses: EnricoMi/publish-unit-test-result-action@v2
          if: always()
          with:
            files: TestResults.trx
      permissions: 
        checks: write
        pull-requests: write

    release:
      name: Release packages
      runs-on: windows-latest
      needs: [setup, build, test]
      if: startsWith(github.ref, 'refs/tags/release-v')
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Download build artifacts
          uses: actions/download-artifact@v3
          with:
            name: build-artifacts

        - name: Restore dependencies
          run: dotnet restore
          
        - name: Package
          run: dotnet pack -c Release --no-build --output nupkgs

        - name: Publish
          run: dotnet nuget push nupkgs/ -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
