name: Build and Test

on:
  pull_request:
    branches: [ "main", "develop"]
    
jobs:
    setup:
      name: Setup
      runs-on: windows-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
          
      - name: 'Install Latest .NET MAUI Workload'
        run: dotnet workload install maui

      - name: Install dependencies
        run: dotnet restore
    build:
      name: Build and Test
      runs-on: windows-latest
      needs: setup
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Build
          run: dotnet build -c Release

        - name: Test
          run: dotnet test -c Release --no-build --verbosity normal --logger "trx;LogFileName=..\..\..\TestResults.trx"

        - name: Publish Test Results
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: TestResults
            path: TestResults.trx